import pytest
from fastapi.testclient import TestClient
from sdpstudio_server.app import create_app
from sdpstudio_server.collaboration_merge import merge_updates, server_merge_available

pytestmark = pytest.mark.skipif(
    not server_merge_available(), reason="collaboration extra not installed"
)


def test_server_merge_accepts_independent_y_crdt_updates():
    import base64

    from pycrdt import Doc, Map

    # Updates generated by Yjs 13.x, matching web/src/collab.ts's root map.
    def decode(value: str) -> bytes:
        return base64.b64decode(value + "=" * (-len(value) % 4), altchars=b"-_")

    first = decode("AQHU-vaWDQAoAQlzZHBzdHVkaW8Gbm9kZTphAXYBAmlkdwFhAA")
    second = decode("AQGGh6LFAQAoAQlzZHBzdHVkaW8Gbm9kZTpiAXYBAmlkdwFiAA")

    merged_update = merge_updates([first, second])
    merged = Doc()
    merged.apply_update(merged_update)
    assert merged.get("sdpstudio", type=Map).to_py() == {
        "node:a": {"id": "a"},
        "node:b": {"id": "b"},
    }


@pytest.mark.skipif(not server_merge_available(), reason="collaboration extra not installed")
def test_websocket_persists_browser_shaped_updates_through_server_merge(tmp_path):
    import base64

    from pycrdt import Doc, Map

    def decode(value: str) -> bytes:
        return base64.b64decode(value + "=" * (-len(value) % 4), altchars=b"-_")

    first = "AQHU-vaWDQAoAQlzZHBzdHVkaW8Gbm9kZTphAXYBAmlkdwFhAA"
    second = "AQGGh6LFAQAoAQlzZHBzdHVkaW8Gbm9kZTpiAXYBAmlkdwFiAA"
    client = TestClient(create_app(tmp_path))
    project = client.post("/api/projects", json={"name": "server-merge"}).json()

    with client.websocket_connect(f"/ws/projects/{project['id']}") as socket:
        assert socket.receive_json()["type"] == "presence"
        socket.send_json({"type": "y_update", "update": first})
        assert socket.receive_json()["type"] == "y_update"
        socket.send_json({"type": "y_update", "update": second})
        assert socket.receive_json()["type"] == "y_update"

    events = client.app.state.store.collaboration_events(project["id"])
    merged = Doc()
    merged.apply_update(merge_updates([decode(event["update"]) for event in events]))
    assert merged.get("sdpstudio", type=Map).to_py() == {
        "node:a": {"id": "a"},
        "node:b": {"id": "b"},
    }
