type Comparison = { left?: { id?: string; status?: string }; right?: { id?: string; status?: string }; duration_delta_seconds?: number; schema?: Record<string, unknown>; node_diffs?: Array<Record<string, unknown>>; metric_deltas?: Record<string, unknown>; source_diff?: { generated_source_available?: boolean; unified_diff?: string | null; [key: string]: unknown }; plan_diff?: { available?: boolean; nodes?: Array<Record<string, unknown>>; reason?: string }; [key: string]: unknown };

export function RunComparisonPanel({ value }: { value: string }) {
  let comparison: Comparison;
  try { comparison = JSON.parse(value) as Comparison; } catch { return <pre className="generated" aria-label="Run comparison">{value}</pre>; }
  const structuralChangeCount = (item: Record<string, unknown>) => {
    if (!item.available || typeof item.diff !== "object" || item.diff === null) return 0;
    const operations = (item.diff as { operations?: unknown }).operations;
    return Array.isArray(operations) ? operations.length : 0;
  };
  return <section id="workspace-view-comparison" className="run-comparison-panel" aria-label="Run comparison"><div className="comparison-summary"><strong>{comparison.left?.id || "left"}</strong> <span>vs</span> <strong>{comparison.right?.id || "right"}</strong>{comparison.duration_delta_seconds !== undefined && <small>{comparison.duration_delta_seconds}s duration delta</small>}</div>{comparison.source_diff && <section aria-label="Generated source differences"><h3>Generated source differences</h3>{comparison.source_diff.unified_diff ? <pre className="generated">{comparison.source_diff.unified_diff}</pre> : <p className="muted">{comparison.source_diff.generated_source_available === false ? "Generated source unavailable for one or both runs." : "No generated source changes."}</p>}</section>}{comparison.plan_diff && <section aria-label="Plan differences"><h3>Plan differences</h3>{comparison.plan_diff.available ? <ul>{(comparison.plan_diff.nodes || []).map((item, index) => <li key={String(item.node_id || index)}>{String(item.node_id || "node")}: {item.available ? `${structuralChangeCount(item)} structural changes` : "plan unavailable"}</li>)}</ul> : <p className="muted">{comparison.plan_diff.reason || "Plan comparison unavailable"}</p>}</section>}{comparison.schema && <section><h3>Schema changes</h3><pre className="generated">{JSON.stringify(comparison.schema, null, 2)}</pre></section>}{comparison.node_diffs && <section><h3>Node changes ({comparison.node_diffs.length})</h3><ul>{comparison.node_diffs.slice(0, 50).map((diff, index) => <li key={index}>{String(diff.node_id || diff.kind || "node change")}</li>)}</ul></section>}{comparison.metric_deltas && <section><h3>Metric deltas</h3><pre className="generated">{JSON.stringify(comparison.metric_deltas, null, 2)}</pre></section>}</section>;
}
