apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sdpstudio.fullname" . }}
data:
  SDPSTUDIO_DATA_ROOT: /data
  SDPSTUDIO_DATABASE_URL: {{ required "database.url is required" .Values.database.url | quote }}
