apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "sdpstudio.fullname" . }}
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  {{- if .Values.storage.storageClassName }}
  storageClassName: {{ .Values.storage.storageClassName }}
  {{- end }}
