# Generated by SDP Studio. The visual model is the source of truth; do not hand edit this file.
from pyspark import pipelines as dp
from pyspark.sql import DataFrame
from pyspark.sql import functions as F

sdpstudio_quality_checks = []


@dp.materialized_view(name='clean_orders')
def clean_orders() -> DataFrame:
    n_source = spark.table('orders')
    n_filter = n_source.filter(F.expr('amount > 0'))
    return n_filter
