"""Generate/check a deterministic TypeScript OpenAPI endpoint catalog and DTOs."""

from __future__ import annotations

import argparse
import json
import re
import tempfile
from pathlib import Path
from typing import Any


def _type_name(name: str) -> str:
    parts = re.split(r"[^A-Za-z0-9]+", name)
    return "".join(part[:1].upper() + part[1:] for part in parts if part) or "Anonymous"


def _ts_type(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return _type_name(str(schema["$ref"]).rsplit("/", 1)[-1])
    if "oneOf" in schema:
        return " | ".join(_ts_type(item) for item in schema["oneOf"])
    if "anyOf" in schema:
        return " | ".join(_ts_type(item) for item in schema["anyOf"])
    if "allOf" in schema:
        return " & ".join(_ts_type(item) for item in schema["allOf"])
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    kind = schema.get("type")
    if kind == "array":
        return f"Array<{_ts_type(schema.get('items', {}))}>"
    if kind == "object" or "additionalProperties" in schema:
        additional = schema.get("additionalProperties")
        return (
            f"Record<string, {_ts_type(additional)}>"
            if isinstance(additional, dict)
            else "Record<string, unknown>"
        )
    return {"string": "string", "integer": "number", "number": "number", "boolean": "boolean"}.get(
        kind, "unknown"
    )


def _render_schema(name: str, schema: dict[str, Any]) -> list[str]:
    interface = _type_name(name)
    if schema.get("type") != "object" and "properties" not in schema:
        return [f"export type {interface} = {_ts_type(schema)};", ""]
    required = set(schema.get("required", []))
    lines = [f"export interface {interface} {{"]
    for property_name in sorted(schema.get("properties", {})):
        property_schema = schema["properties"][property_name]
        optional = "" if property_name in required else "?"
        safe_name = property_name if property_name.isidentifier() else json.dumps(property_name)
        lines.append(f"  {safe_name}{optional}: {_ts_type(property_schema)};")
    lines.extend(["}", ""])
    return lines


def render_client(document: dict[str, Any]) -> str:
    paths_document = document.get("paths") or {}
    paths = sorted(str(path) for path in paths_document)
    operations = sorted(
        (str(path), str(method).lower())
        for path, item in paths_document.items()
        if isinstance(item, dict)
        for method in item
        if str(method).lower() in {"get", "post", "put", "patch", "delete", "options", "head"}
    )
    lines = [
        "// Generated by scripts/openapi_client.py; do not edit manually.",
        "",
        "export type OpenApiPrimitive = string | number | boolean | null;",
        "",
    ]
    schemas = document.get("components", {}).get("schemas", {})
    for name in sorted(schemas):
        lines.extend(_render_schema(str(name), schemas[name]))
    lines.extend(
        [
            "export const OPENAPI_PATHS = [",
        ]
    )
    lines.extend(f'  "{path}",' for path in paths)
    lines.extend(
        [
            "] as const;",
            "export type OpenApiPath = (typeof OPENAPI_PATHS)[number];",
            "export const OPENAPI_OPERATIONS = [",
        ]
    )
    lines.extend(f'  {{ path: "{path}", method: "{method}" }},' for path, method in operations)
    lines.extend(
        [
            "] as const;",
            "export type OpenApiOperation = (typeof OPENAPI_OPERATIONS)[number];",
            "",
        ]
    )
    return "\n".join(lines)


def generate(input_path: Path, output_path: Path, *, check: bool = False) -> bool:
    document = json.loads(input_path.read_text(encoding="utf-8"))
    rendered = render_client(document)
    if check:
        return output_path.exists() and output_path.read_text(encoding="utf-8") == rendered
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(rendered, encoding="utf-8")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path)
    parser.add_argument("--from-app", action="store_true")
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.from_app:
        from sdpstudio_server.app import create_app

        with tempfile.TemporaryDirectory(prefix="sdpstudio-openapi-") as directory:
            document = create_app(Path(directory)).openapi()
        rendered = render_client(document)
        if args.check:
            return int(
                not (args.output.exists() and args.output.read_text(encoding="utf-8") == rendered)
            )
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(rendered, encoding="utf-8")
        return 0
    if args.input is None:
        parser.error("--input or --from-app is required")
    if generate(args.input, args.output, check=args.check):
        return 0
    print(f"Generated OpenAPI client is stale: {args.output}")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
