"""Verify concrete evidence for consolidated spec-report remediations.

This is intentionally a source-and-test evidence check, not a claim that every
subjective UX requirement is complete. It keeps resolved high-risk contracts
from regressing while the remaining report items are implemented.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


def audit(root: Path) -> dict[str, Any]:
    def exists(relative: str) -> bool:
        return (root / relative).exists()

    def contains(relative: str, needle: str) -> bool:
        path = root / relative
        return path.exists() and needle in path.read_text(encoding="utf-8")

    checks = [
        ("graph-save-preserves-config", "tests/test_storage_api.py", "amount > 10"),
        ("graph-mode-compatibility", "tests/test_core.py", "mode_incompatible"),
        (
            "persisted-schema-entities",
            "python/sdpstudio_core/models.py",
            "class EnvironmentReference",
        ),
        ("operator-contract-metadata", "python/sdpstudio_core/operators.py", "contract_metadata"),
        ("ir-origin-source-location", "tests/test_ir.py", "retains_origin_and_source_location"),
        ("browser-workflow-coverage", "web/e2e/studio.workflow.spec.ts", "generated SQL"),
        (
            "parameter-editor",
            "web/src/features/inspector/ParameterEditor.tsx",
            "Project parameters",
        ),
        ("project-file-editor", "web/src/features/explorer/FileEditor.tsx", "reload before saving"),
        ("explorer-mutations", "web/src/features/explorer/FileEditor.tsx", "Create directory"),
        ("ownership-reconciliation", "tests/test_reconcile.py", "reconcile"),
        ("python-sql-roundtrip-suite", "tests/test_reconcile.py", "regenerate_deterministically"),
        ("durable-run-worker", "python/sdpstudio_server/run_worker.py", "heartbeat"),
        ("spark-plan-capture", "python/sdpstudio_runners/local.py", "spark_dataframe_explain"),
        (
            "incremental-event-summary",
            "python/sdpstudio_core/debug.py",
            "summarize_spark_event_stream",
        ),
        ("spark-row-trace-instrumentation", "python/sdpstudio_codegen/preview.py", "include_trace"),
        ("run-plan-comparison", "python/sdpstudio_server/app.py", '"plan_diff": plan_comparison'),
        ("quality-suite", "python/sdpstudio_core/quality_suite.py", "quality.yaml"),
        ("quality-suite-api", "python/sdpstudio_server/app.py", "quality/suite/evaluate"),
        (
            "quality-runtime-hook",
            "python/sdpstudio_codegen/python_backend.py",
            "_sdpstudio_quality_check",
        ),
        (
            "databricks-profile-editor",
            "web/src/features/runtime/RuntimeProfilePanel.tsx",
            "Databricks settings",
        ),
        (
            "kubernetes-profile-editor",
            "web/src/features/runtime/RuntimeProfilePanel.tsx",
            "Kubernetes settings",
        ),
        (
            "kubernetes-run-details",
            "web/src/features/runs/KubernetesRunPanel.tsx",
            "Kubernetes run details",
        ),
        (
            "typed-inspector-fields",
            "web/src/features/inspector/SchemaInspector.tsx",
            'type === "number"',
        ),
        ("git-hook-hardening", "python/sdpstudio_server/git_service.py", "hooksPath"),
        ("browser-security-headers", "python/sdpstudio_server/app.py", "frame-ancestors"),
        ("oidc-nonce", "python/sdpstudio_server/oidc.py", "validate_id_token_nonce"),
        ("secret-keyring-fallback", "python/sdpstudio_server/secrets.py", "keyring"),
        ("plugin-extension-groups", "python/sdpstudio_core/plugins.py", "diagnostic-rule-pack"),
        ("plugin-inventory-api", "python/sdpstudio_server/app.py", "/api/plugins"),
        ("web-layout-worker", "web/src/features/canvas/layout.ts", "new Worker"),
        (
            "accessible-graph-outline",
            "web/src/features/canvas/GraphOutline.tsx",
            "Pipeline outline",
        ),
        ("python-golden", "tests/golden/python_basic_generated.py", "Generated by SDP Studio"),
        ("sql-golden", "tests/golden/sql_basic_generated.sql", "Generated by SDP Studio"),
        (
            "cdc-visual-example",
            "examples/cdc-auto-scd1/.sdpstudio/pipelines/main.sdpstudio.yaml",
            "auto_cdc_scd1",
        ),
        ("quality-example-suite", "examples/retail-etl/.sdpstudio/tests/quality.yaml", "checks:"),
        ("provider-run-metadata", "tests/test_storage_api.py", "provider_identity"),
        ("git-collaboration-coordination", "python/sdpstudio_server/app.py", "before git"),
        ("git-path-staging", "web/src/main.tsx", "stageGitPath"),
        ("git-sync-controls", "web/src/main.tsx", "Git synchronization"),
        ("git-conflict-preview", "python/sdpstudio_server/git_service.py", "conflict_versions"),
        ("migration-downgrade", "tests/test_migrations.py", "downgrades_cleanly"),
        ("extended-qualification-script", "scripts/qualify.py", "--kubernetes"),
        (
            "kubernetes-immutable-staging",
            "python/sdpstudio_runners/profiles.py",
            "staged-artifact-manifest",
        ),
        (
            "async-runtime-dispatch-boundary",
            "python/sdpstudio_server/runtime_dispatch.py",
            "class RuntimeDispatch",
        ),
    ]
    results = [
        {"id": identifier, "passed": contains(path, needle)} for identifier, path, needle in checks
    ]
    return {
        "schema": 1,
        "passed": all(item["passed"] for item in results),
        "checks": results,
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path.cwd())
    parser.add_argument("--output", type=Path, default=Path("dist/report-audit.json"))
    args = parser.parse_args()
    root = args.root.resolve()
    report = audit(root)
    output = args.output if args.output.is_absolute() else root / args.output
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps({"passed": report["passed"], "output": str(output)}, sort_keys=True))
    return 0 if report["passed"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
