// Generated by scripts/openapi_client.py; do not edit manually.

export type OpenApiPrimitive = string | number | boolean | null;

export interface BranchDeleteRequest {
  force?: boolean;
  name: string;
}

export interface BranchRequest {
  name: string;
}

export interface CloneProjectRequest {
  branch?: string | unknown;
  name: string;
  remote_url: string;
}

export interface CommitRequest {
  message: string;
}

export interface CompareRunsRequest {
  left_run_id: string;
  right_run_id: string;
}

export interface ConflictResolutionRequest {
  path: string;
  strategy: "ours" | "theirs";
}

export interface CreateProjectRequest {
  example?: string | unknown;
  name: string;
}

export interface DiagnosticRequest {
  context?: Record<string, unknown>;
  error_class?: string | unknown;
  message?: string;
}

export interface DryRunRequest {
  runtime_profile_id?: string | unknown;
}

export interface Edge {
  from: PortRef;
  id?: string;
  to: PortRef;
}

export interface EventLogRequest {
  events: Array<Record<string, unknown>>;
}

export interface ExplainPlanRequest {
  before?: Record<string, unknown> | unknown;
  explain: string;
}

export interface FileDirectoryRequest {
  path: string;
}

export interface FileRenameRequest {
  etag?: string | unknown;
  new_path: string;
  old_path: string;
}

export interface FileWriteRequest {
  content: string;
  etag?: string | unknown;
}

export interface GeneratedFile {
  content: string;
  path: string;
  sha256: string;
}

export interface GenerationResult {
  changed_files?: Array<string>;
  diff_summary?: Record<string, number>;
  files: Array<GeneratedFile>;
  problems?: Array<Problem>;
  source_map: Array<SourceRange>;
}

export interface GitPathsRequest {
  paths?: Array<string>;
}

export interface GitSyncRequest {
  branch?: string | unknown;
  remote?: string;
}

export interface GlobalScheduleRequest {
  concurrency_policy?: string;
  cron: string;
  enabled?: boolean;
  missed_run_policy?: string;
  mode?: string;
  name: string;
  project_id: string;
  runtime_profile_id?: string | unknown;
  timezone?: string;
}

export interface HTTPValidationError {
  detail?: Array<ValidationError>;
}

export interface HistoryCheckpointRequest {
  name: string;
}

export interface ImportPythonRequest {
  path?: string;
  source: string;
}

export interface ImportSqlRequest {
  path?: string;
  source: string;
}

export interface LoginRequest {
  password: string;
  username: string;
}

export interface Node {
  config?: Record<string, unknown>;
  id?: string;
  operatorVersion?: number;
  position?: Position;
  type: string;
}

export interface NodeSnapshotRequest {
  metrics?: Record<string, unknown> | unknown;
  node_id: string;
  plan_artifact_id?: string | unknown;
  profile?: Record<string, unknown> | unknown;
  schema?: Array<Record<string, unknown>> | unknown;
}

export interface PipelineDocument {
  edges?: Array<Edge>;
  name?: string;
  nodes?: Array<Node>;
  pipelineId?: string;
  revision?: number;
  schemaVersion?: number;
}

export interface PortRef {
  node: string;
  port?: string;
}

export interface Position {
  x?: number;
  y?: number;
}

export interface PreviewRequest {
  cache_ttl_seconds?: number;
  confirm_sink_test?: boolean;
  force_refresh?: boolean;
  include_plan?: boolean;
  include_profile?: boolean;
  limit?: number;
  node_id: string;
  profile_max_columns?: number;
  profile_max_rows?: number;
  profile_top_values?: number;
  runtime_profile_id?: string | unknown;
  sampling_fraction?: number;
  seed?: number;
  timeout_seconds?: number;
}

export interface Problem {
  code: string;
  details?: Record<string, unknown>;
  doc_link?: string | unknown;
  line?: number | unknown;
  message: string;
  node_id?: string | unknown;
  path?: string | unknown;
  probable_cause?: string | unknown;
  remediation?: string | unknown;
  severity: "info" | "warning" | "error";
}

export interface ProfileDiffRequest {
  after: Record<string, unknown>;
  before: Record<string, unknown>;
}

export interface ProfileRowsRequest {
  include_sensitive_metrics?: boolean;
  max_columns?: number;
  max_rows?: number;
  rows?: Array<Record<string, unknown>>;
  top_values?: number;
}

export interface ProjectResponse {
  id: string;
  name: string;
  path?: string | unknown;
}

export interface ProjectUpdateRequest {
  name: string;
}

export interface QualityEvaluateRequest {
  limit?: number;
  node_id: string;
  rows: Array<Record<string, unknown>>;
}

export interface QualitySuiteEvaluateRequest {
  automatic?: boolean;
  limit?: number;
  mode?: string | unknown;
  rows_by_check?: Record<string, Array<Record<string, unknown>>>;
}

export interface RedactionPreviewRequest {
  payload: unknown;
}

export interface RemoteRequest {
  name?: string;
  url: string;
}

export interface ReviewRequest {
  base?: string;
  body?: string;
  head: string;
  provider?: string;
  remote?: string;
  title: string;
}

export interface RowTraceRequest {
  limit?: number;
  node_id: string;
  rows?: Array<Record<string, unknown>>;
  rows_by_source?: Record<string, Array<Record<string, unknown>>>;
}

export interface RunRequest {
  mode?: string;
  runtime_profile_id?: string | unknown;
  selected?: Array<string>;
}

export interface RuntimeCapabilities {
  adapter?: string;
  append_flow?: boolean;
  auto_cdc_scd1?: boolean;
  available?: boolean;
  databricks?: boolean;
  details?: Record<string, unknown>;
  downgrade_map?: Record<string, string>;
  dry_run?: boolean;
  extensions?: Record<string, RuntimeExtension>;
  full_refresh?: boolean;
  kubernetes?: boolean;
  materialized_view?: boolean;
  portability?: "portable" | "provider" | "unknown";
  provider?: string | unknown;
  provider_extensions?: Record<string, RuntimeExtension>;
  python?: boolean;
  sdp?: boolean;
  selective_refresh?: boolean;
  sink?: boolean;
  sinks?: boolean;
  spark_connect?: boolean;
  spark_version?: string | unknown;
  sql?: boolean;
  streaming_table?: boolean;
  temporary_view?: boolean;
}

export interface RuntimeExtension {
  capabilities?: Array<string>;
  details?: Record<string, unknown>;
  version?: string | unknown;
}

export interface RuntimeProfileRequest {
  adapter: string;
  config?: Record<string, unknown>;
  is_protected?: boolean;
  name: string;
}

export interface RuntimeProfileResponse {
  adapter: string;
  config?: Record<string, unknown>;
  created_at?: string | unknown;
  id: string;
  is_protected?: boolean;
  name: string;
  updated_at?: string | unknown;
}

export interface RuntimeProfileUpdateRequest {
  adapter?: string | unknown;
  config?: Record<string, unknown> | unknown;
  is_protected?: boolean | unknown;
  name?: string | unknown;
}

export interface ScheduleRequest {
  concurrency_policy?: string;
  cron: string;
  enabled?: boolean;
  missed_run_policy?: string;
  mode?: string;
  name: string;
  runtime_profile_id?: string | unknown;
  timezone?: string;
}

export interface ScheduleUpdateRequest {
  concurrency_policy?: string | unknown;
  cron?: string | unknown;
  enabled?: boolean | unknown;
  missed_run_policy?: string | unknown;
  mode?: string | unknown;
  name?: string | unknown;
  runtime_profile_id?: string | unknown;
  timezone?: string | unknown;
}

export interface SchemaDiffRequest {
  after: Array<Record<string, unknown>>;
  allow_added?: boolean;
  before: Array<Record<string, unknown>>;
  contract_mode?: string;
}

export interface SecretRequest {
  name: string;
  value: string;
}

export interface SourceRange {
  content_hash?: string | unknown;
  end_column?: number | unknown;
  end_line: number;
  file: string;
  node_id: string;
  object_id?: string | unknown;
  start_column?: number | unknown;
  start_line: number;
}

export interface StashRequest {
  action: string;
  message?: string | unknown;
}

export interface TagRequest {
  message?: string | unknown;
  name: string;
}

export interface UserRequest {
  password: string;
  role?: string;
  username: string;
}

export interface UserRoleRequest {
  role: "viewer" | "editor" | "admin";
}

export interface ValidationError {
  ctx?: Record<string, unknown>;
  input?: unknown;
  loc: Array<string | number>;
  msg: string;
  type: string;
}

export const OPENAPI_PATHS = [
  "/",
  "/api/auth/audit",
  "/api/auth/login",
  "/api/auth/logout",
  "/api/auth/me",
  "/api/auth/oidc/callback",
  "/api/auth/oidc/config",
  "/api/auth/oidc/start",
  "/api/auth/users",
  "/api/auth/users/{username}",
  "/api/debug/diagnostics",
  "/api/debug/event-log/analyze",
  "/api/debug/plan/parse",
  "/api/debug/profile",
  "/api/debug/profile-diff",
  "/api/debug/redaction-preview",
  "/api/debug/schema-diff",
  "/api/debug/streaming/analyze",
  "/api/doctor",
  "/api/import/python",
  "/api/import/sql",
  "/api/operators",
  "/api/pipelines/{pipeline_id}",
  "/api/pipelines/{pipeline_id}/compatibility",
  "/api/pipelines/{pipeline_id}/preview",
  "/api/pipelines/{pipeline_id}/runs",
  "/api/pipelines/{pipeline_id}/validate",
  "/api/plugins",
  "/api/projects",
  "/api/projects/clone",
  "/api/projects/{project_id}",
  "/api/projects/{project_id}/catalog",
  "/api/projects/{project_id}/code",
  "/api/projects/{project_id}/collaboration/capabilities",
  "/api/projects/{project_id}/debug/compare-runs",
  "/api/projects/{project_id}/debug/plan",
  "/api/projects/{project_id}/debug/row-trace/execute",
  "/api/projects/{project_id}/debug/row-trace/{node_id}",
  "/api/projects/{project_id}/debug/schema-timeline",
  "/api/projects/{project_id}/dry-run",
  "/api/projects/{project_id}/files",
  "/api/projects/{project_id}/files/directory",
  "/api/projects/{project_id}/files/rename",
  "/api/projects/{project_id}/files/{path}",
  "/api/projects/{project_id}/generate",
  "/api/projects/{project_id}/generate-sql",
  "/api/projects/{project_id}/git/blob-diff",
  "/api/projects/{project_id}/git/branches",
  "/api/projects/{project_id}/git/branches/switch",
  "/api/projects/{project_id}/git/checkout",
  "/api/projects/{project_id}/git/commit",
  "/api/projects/{project_id}/git/conflicts",
  "/api/projects/{project_id}/git/conflicts/resolve",
  "/api/projects/{project_id}/git/conflicts/{path}",
  "/api/projects/{project_id}/git/diff",
  "/api/projects/{project_id}/git/fetch",
  "/api/projects/{project_id}/git/graph-diff",
  "/api/projects/{project_id}/git/init",
  "/api/projects/{project_id}/git/log",
  "/api/projects/{project_id}/git/pull",
  "/api/projects/{project_id}/git/push",
  "/api/projects/{project_id}/git/remotes",
  "/api/projects/{project_id}/git/repository",
  "/api/projects/{project_id}/git/review",
  "/api/projects/{project_id}/git/reviews",
  "/api/projects/{project_id}/git/stage",
  "/api/projects/{project_id}/git/stash",
  "/api/projects/{project_id}/git/status",
  "/api/projects/{project_id}/git/tags",
  "/api/projects/{project_id}/git/unstage",
  "/api/projects/{project_id}/history",
  "/api/projects/{project_id}/history/checkpoints",
  "/api/projects/{project_id}/history/{revision_id}",
  "/api/projects/{project_id}/history/{revision_id}/diff",
  "/api/projects/{project_id}/history/{revision_id}/restore",
  "/api/projects/{project_id}/history/{snapshot_id}",
  "/api/projects/{project_id}/history/{snapshot_id}/diff",
  "/api/projects/{project_id}/history/{snapshot_id}/restore",
  "/api/projects/{project_id}/import",
  "/api/projects/{project_id}/import/python",
  "/api/projects/{project_id}/import/sql",
  "/api/projects/{project_id}/pipeline",
  "/api/projects/{project_id}/pipelines",
  "/api/projects/{project_id}/preview",
  "/api/projects/{project_id}/quality/evaluate",
  "/api/projects/{project_id}/quality/suite/evaluate",
  "/api/projects/{project_id}/reconcile/python",
  "/api/projects/{project_id}/reconcile/sql",
  "/api/projects/{project_id}/retention/cleanup",
  "/api/projects/{project_id}/reviews",
  "/api/projects/{project_id}/runs",
  "/api/projects/{project_id}/runs/{run_id}/node-snapshots",
  "/api/projects/{project_id}/schedules",
  "/api/projects/{project_id}/schedules/{schedule_id}/run-now",
  "/api/projects/{project_id}/tree",
  "/api/projects/{project_id}/validate",
  "/api/projects/{project_id}/validate-capabilities",
  "/api/projects/{project_id}/validate-model",
  "/api/runs/compare",
  "/api/runs/{run_id}",
  "/api/runs/{run_id}/artifacts",
  "/api/runs/{run_id}/artifacts/{artifact_path}",
  "/api/runs/{run_id}/cancel",
  "/api/runs/{run_id}/debug-bundle",
  "/api/runs/{run_id}/debug-bundle/preview",
  "/api/runs/{run_id}/events",
  "/api/runs/{run_id}/kubernetes/events",
  "/api/runs/{run_id}/kubernetes/logs",
  "/api/runs/{run_id}/kubernetes/probe",
  "/api/runs/{run_id}/kubernetes/status",
  "/api/runs/{run_id}/node-snapshots",
  "/api/runs/{run_id}/nodes/{node_id}",
  "/api/runs/{run_id}/plan",
  "/api/runtime-profiles",
  "/api/runtime-profiles/{profile_id}",
  "/api/runtime-profiles/{profile_id}/probe",
  "/api/runtime-profiles/{profile_id}/test",
  "/api/schedules",
  "/api/schedules/{schedule_id}",
  "/api/schema/pipeline",
  "/api/secrets",
  "/api/secrets/rotate-key",
  "/api/secrets/{name}",
  "/api/secrets/{secret_id}",
  "/api/v1/auth/audit",
  "/api/v1/auth/login",
  "/api/v1/auth/logout",
  "/api/v1/auth/me",
  "/api/v1/auth/oidc/callback",
  "/api/v1/auth/oidc/config",
  "/api/v1/auth/oidc/start",
  "/api/v1/auth/users",
  "/api/v1/auth/users/{username}",
  "/api/v1/debug/diagnostics",
  "/api/v1/debug/event-log/analyze",
  "/api/v1/debug/plan/parse",
  "/api/v1/debug/profile",
  "/api/v1/debug/profile-diff",
  "/api/v1/debug/redaction-preview",
  "/api/v1/debug/schema-diff",
  "/api/v1/debug/streaming/analyze",
  "/api/v1/doctor",
  "/api/v1/import/python",
  "/api/v1/import/sql",
  "/api/v1/operators",
  "/api/v1/pipelines/{pipeline_id}",
  "/api/v1/pipelines/{pipeline_id}/compatibility",
  "/api/v1/pipelines/{pipeline_id}/preview",
  "/api/v1/pipelines/{pipeline_id}/runs",
  "/api/v1/pipelines/{pipeline_id}/validate",
  "/api/v1/plugins",
  "/api/v1/projects",
  "/api/v1/projects/clone",
  "/api/v1/projects/{project_id}",
  "/api/v1/projects/{project_id}/catalog",
  "/api/v1/projects/{project_id}/code",
  "/api/v1/projects/{project_id}/collaboration/capabilities",
  "/api/v1/projects/{project_id}/debug/compare-runs",
  "/api/v1/projects/{project_id}/debug/plan",
  "/api/v1/projects/{project_id}/debug/row-trace/execute",
  "/api/v1/projects/{project_id}/debug/row-trace/{node_id}",
  "/api/v1/projects/{project_id}/debug/schema-timeline",
  "/api/v1/projects/{project_id}/dry-run",
  "/api/v1/projects/{project_id}/files",
  "/api/v1/projects/{project_id}/files/directory",
  "/api/v1/projects/{project_id}/files/rename",
  "/api/v1/projects/{project_id}/files/{path}",
  "/api/v1/projects/{project_id}/generate",
  "/api/v1/projects/{project_id}/generate-sql",
  "/api/v1/projects/{project_id}/git/blob-diff",
  "/api/v1/projects/{project_id}/git/branches",
  "/api/v1/projects/{project_id}/git/branches/switch",
  "/api/v1/projects/{project_id}/git/checkout",
  "/api/v1/projects/{project_id}/git/commit",
  "/api/v1/projects/{project_id}/git/conflicts",
  "/api/v1/projects/{project_id}/git/conflicts/resolve",
  "/api/v1/projects/{project_id}/git/conflicts/{path}",
  "/api/v1/projects/{project_id}/git/diff",
  "/api/v1/projects/{project_id}/git/fetch",
  "/api/v1/projects/{project_id}/git/graph-diff",
  "/api/v1/projects/{project_id}/git/init",
  "/api/v1/projects/{project_id}/git/log",
  "/api/v1/projects/{project_id}/git/pull",
  "/api/v1/projects/{project_id}/git/push",
  "/api/v1/projects/{project_id}/git/remotes",
  "/api/v1/projects/{project_id}/git/repository",
  "/api/v1/projects/{project_id}/git/review",
  "/api/v1/projects/{project_id}/git/reviews",
  "/api/v1/projects/{project_id}/git/stage",
  "/api/v1/projects/{project_id}/git/stash",
  "/api/v1/projects/{project_id}/git/status",
  "/api/v1/projects/{project_id}/git/tags",
  "/api/v1/projects/{project_id}/git/unstage",
  "/api/v1/projects/{project_id}/history",
  "/api/v1/projects/{project_id}/history/checkpoints",
  "/api/v1/projects/{project_id}/history/{revision_id}",
  "/api/v1/projects/{project_id}/history/{revision_id}/diff",
  "/api/v1/projects/{project_id}/history/{revision_id}/restore",
  "/api/v1/projects/{project_id}/history/{snapshot_id}",
  "/api/v1/projects/{project_id}/history/{snapshot_id}/diff",
  "/api/v1/projects/{project_id}/history/{snapshot_id}/restore",
  "/api/v1/projects/{project_id}/import",
  "/api/v1/projects/{project_id}/import/python",
  "/api/v1/projects/{project_id}/import/sql",
  "/api/v1/projects/{project_id}/pipeline",
  "/api/v1/projects/{project_id}/pipelines",
  "/api/v1/projects/{project_id}/preview",
  "/api/v1/projects/{project_id}/quality/evaluate",
  "/api/v1/projects/{project_id}/quality/suite/evaluate",
  "/api/v1/projects/{project_id}/reconcile/python",
  "/api/v1/projects/{project_id}/reconcile/sql",
  "/api/v1/projects/{project_id}/retention/cleanup",
  "/api/v1/projects/{project_id}/reviews",
  "/api/v1/projects/{project_id}/runs",
  "/api/v1/projects/{project_id}/runs/{run_id}/node-snapshots",
  "/api/v1/projects/{project_id}/schedules",
  "/api/v1/projects/{project_id}/schedules/{schedule_id}/run-now",
  "/api/v1/projects/{project_id}/tree",
  "/api/v1/projects/{project_id}/validate",
  "/api/v1/projects/{project_id}/validate-capabilities",
  "/api/v1/projects/{project_id}/validate-model",
  "/api/v1/runs/compare",
  "/api/v1/runs/{run_id}",
  "/api/v1/runs/{run_id}/artifacts",
  "/api/v1/runs/{run_id}/artifacts/{artifact_path}",
  "/api/v1/runs/{run_id}/cancel",
  "/api/v1/runs/{run_id}/debug-bundle",
  "/api/v1/runs/{run_id}/debug-bundle/preview",
  "/api/v1/runs/{run_id}/events",
  "/api/v1/runs/{run_id}/kubernetes/events",
  "/api/v1/runs/{run_id}/kubernetes/logs",
  "/api/v1/runs/{run_id}/kubernetes/probe",
  "/api/v1/runs/{run_id}/kubernetes/status",
  "/api/v1/runs/{run_id}/node-snapshots",
  "/api/v1/runs/{run_id}/nodes/{node_id}",
  "/api/v1/runs/{run_id}/plan",
  "/api/v1/runtime-profiles",
  "/api/v1/runtime-profiles/{profile_id}",
  "/api/v1/runtime-profiles/{profile_id}/probe",
  "/api/v1/runtime-profiles/{profile_id}/test",
  "/api/v1/schedules",
  "/api/v1/schedules/{schedule_id}",
  "/api/v1/schema/pipeline",
  "/api/v1/secrets",
  "/api/v1/secrets/rotate-key",
  "/api/v1/secrets/{name}",
  "/api/v1/secrets/{secret_id}",
  "/health",
  "/ready",
] as const;
export type OpenApiPath = (typeof OPENAPI_PATHS)[number];
export const OPENAPI_OPERATIONS = [
  { path: "/", method: "get" },
  { path: "/api/auth/audit", method: "get" },
  { path: "/api/auth/login", method: "post" },
  { path: "/api/auth/logout", method: "post" },
  { path: "/api/auth/me", method: "get" },
  { path: "/api/auth/oidc/callback", method: "get" },
  { path: "/api/auth/oidc/config", method: "get" },
  { path: "/api/auth/oidc/start", method: "get" },
  { path: "/api/auth/users", method: "get" },
  { path: "/api/auth/users", method: "post" },
  { path: "/api/auth/users/{username}", method: "patch" },
  { path: "/api/debug/diagnostics", method: "post" },
  { path: "/api/debug/event-log/analyze", method: "post" },
  { path: "/api/debug/plan/parse", method: "post" },
  { path: "/api/debug/profile", method: "post" },
  { path: "/api/debug/profile-diff", method: "post" },
  { path: "/api/debug/redaction-preview", method: "post" },
  { path: "/api/debug/schema-diff", method: "post" },
  { path: "/api/debug/streaming/analyze", method: "post" },
  { path: "/api/doctor", method: "get" },
  { path: "/api/import/python", method: "post" },
  { path: "/api/import/sql", method: "post" },
  { path: "/api/operators", method: "get" },
  { path: "/api/pipelines/{pipeline_id}", method: "get" },
  { path: "/api/pipelines/{pipeline_id}", method: "put" },
  { path: "/api/pipelines/{pipeline_id}/compatibility", method: "get" },
  { path: "/api/pipelines/{pipeline_id}/preview", method: "post" },
  { path: "/api/pipelines/{pipeline_id}/runs", method: "post" },
  { path: "/api/pipelines/{pipeline_id}/validate", method: "post" },
  { path: "/api/plugins", method: "get" },
  { path: "/api/projects", method: "get" },
  { path: "/api/projects", method: "post" },
  { path: "/api/projects/clone", method: "post" },
  { path: "/api/projects/{project_id}", method: "delete" },
  { path: "/api/projects/{project_id}", method: "get" },
  { path: "/api/projects/{project_id}", method: "patch" },
  { path: "/api/projects/{project_id}/catalog", method: "get" },
  { path: "/api/projects/{project_id}/code", method: "get" },
  { path: "/api/projects/{project_id}/collaboration/capabilities", method: "get" },
  { path: "/api/projects/{project_id}/debug/compare-runs", method: "post" },
  { path: "/api/projects/{project_id}/debug/plan", method: "get" },
  { path: "/api/projects/{project_id}/debug/row-trace/execute", method: "post" },
  { path: "/api/projects/{project_id}/debug/row-trace/{node_id}", method: "get" },
  { path: "/api/projects/{project_id}/debug/schema-timeline", method: "get" },
  { path: "/api/projects/{project_id}/dry-run", method: "post" },
  { path: "/api/projects/{project_id}/files", method: "get" },
  { path: "/api/projects/{project_id}/files/directory", method: "post" },
  { path: "/api/projects/{project_id}/files/rename", method: "post" },
  { path: "/api/projects/{project_id}/files/{path}", method: "delete" },
  { path: "/api/projects/{project_id}/files/{path}", method: "get" },
  { path: "/api/projects/{project_id}/files/{path}", method: "put" },
  { path: "/api/projects/{project_id}/generate", method: "post" },
  { path: "/api/projects/{project_id}/generate-sql", method: "post" },
  { path: "/api/projects/{project_id}/git/blob-diff", method: "get" },
  { path: "/api/projects/{project_id}/git/branches", method: "delete" },
  { path: "/api/projects/{project_id}/git/branches", method: "get" },
  { path: "/api/projects/{project_id}/git/branches", method: "post" },
  { path: "/api/projects/{project_id}/git/branches/switch", method: "post" },
  { path: "/api/projects/{project_id}/git/checkout", method: "post" },
  { path: "/api/projects/{project_id}/git/commit", method: "post" },
  { path: "/api/projects/{project_id}/git/conflicts", method: "get" },
  { path: "/api/projects/{project_id}/git/conflicts/resolve", method: "post" },
  { path: "/api/projects/{project_id}/git/conflicts/{path}", method: "get" },
  { path: "/api/projects/{project_id}/git/diff", method: "get" },
  { path: "/api/projects/{project_id}/git/fetch", method: "post" },
  { path: "/api/projects/{project_id}/git/graph-diff", method: "get" },
  { path: "/api/projects/{project_id}/git/init", method: "post" },
  { path: "/api/projects/{project_id}/git/log", method: "get" },
  { path: "/api/projects/{project_id}/git/pull", method: "post" },
  { path: "/api/projects/{project_id}/git/push", method: "post" },
  { path: "/api/projects/{project_id}/git/remotes", method: "get" },
  { path: "/api/projects/{project_id}/git/remotes", method: "post" },
  { path: "/api/projects/{project_id}/git/repository", method: "get" },
  { path: "/api/projects/{project_id}/git/review", method: "post" },
  { path: "/api/projects/{project_id}/git/reviews", method: "get" },
  { path: "/api/projects/{project_id}/git/stage", method: "post" },
  { path: "/api/projects/{project_id}/git/stash", method: "get" },
  { path: "/api/projects/{project_id}/git/stash", method: "post" },
  { path: "/api/projects/{project_id}/git/status", method: "get" },
  { path: "/api/projects/{project_id}/git/tags", method: "get" },
  { path: "/api/projects/{project_id}/git/tags", method: "post" },
  { path: "/api/projects/{project_id}/git/unstage", method: "post" },
  { path: "/api/projects/{project_id}/history", method: "get" },
  { path: "/api/projects/{project_id}/history/checkpoints", method: "post" },
  { path: "/api/projects/{project_id}/history/{revision_id}", method: "get" },
  { path: "/api/projects/{project_id}/history/{revision_id}/diff", method: "get" },
  { path: "/api/projects/{project_id}/history/{revision_id}/restore", method: "post" },
  { path: "/api/projects/{project_id}/history/{snapshot_id}", method: "get" },
  { path: "/api/projects/{project_id}/history/{snapshot_id}/diff", method: "get" },
  { path: "/api/projects/{project_id}/history/{snapshot_id}/restore", method: "post" },
  { path: "/api/projects/{project_id}/import", method: "post" },
  { path: "/api/projects/{project_id}/import/python", method: "post" },
  { path: "/api/projects/{project_id}/import/sql", method: "post" },
  { path: "/api/projects/{project_id}/pipeline", method: "get" },
  { path: "/api/projects/{project_id}/pipeline", method: "put" },
  { path: "/api/projects/{project_id}/pipelines", method: "get" },
  { path: "/api/projects/{project_id}/pipelines", method: "post" },
  { path: "/api/projects/{project_id}/preview", method: "post" },
  { path: "/api/projects/{project_id}/quality/evaluate", method: "post" },
  { path: "/api/projects/{project_id}/quality/suite/evaluate", method: "post" },
  { path: "/api/projects/{project_id}/reconcile/python", method: "post" },
  { path: "/api/projects/{project_id}/reconcile/sql", method: "post" },
  { path: "/api/projects/{project_id}/retention/cleanup", method: "post" },
  { path: "/api/projects/{project_id}/reviews", method: "get" },
  { path: "/api/projects/{project_id}/runs", method: "get" },
  { path: "/api/projects/{project_id}/runs", method: "post" },
  { path: "/api/projects/{project_id}/runs/{run_id}/node-snapshots", method: "post" },
  { path: "/api/projects/{project_id}/schedules", method: "get" },
  { path: "/api/projects/{project_id}/schedules", method: "post" },
  { path: "/api/projects/{project_id}/schedules/{schedule_id}/run-now", method: "post" },
  { path: "/api/projects/{project_id}/tree", method: "get" },
  { path: "/api/projects/{project_id}/validate", method: "post" },
  { path: "/api/projects/{project_id}/validate-capabilities", method: "post" },
  { path: "/api/projects/{project_id}/validate-model", method: "post" },
  { path: "/api/runs/compare", method: "post" },
  { path: "/api/runs/{run_id}", method: "get" },
  { path: "/api/runs/{run_id}/artifacts", method: "get" },
  { path: "/api/runs/{run_id}/artifacts/{artifact_path}", method: "get" },
  { path: "/api/runs/{run_id}/cancel", method: "post" },
  { path: "/api/runs/{run_id}/debug-bundle", method: "get" },
  { path: "/api/runs/{run_id}/debug-bundle", method: "post" },
  { path: "/api/runs/{run_id}/debug-bundle/preview", method: "get" },
  { path: "/api/runs/{run_id}/events", method: "get" },
  { path: "/api/runs/{run_id}/kubernetes/events", method: "get" },
  { path: "/api/runs/{run_id}/kubernetes/logs", method: "get" },
  { path: "/api/runs/{run_id}/kubernetes/probe", method: "get" },
  { path: "/api/runs/{run_id}/kubernetes/status", method: "get" },
  { path: "/api/runs/{run_id}/node-snapshots", method: "get" },
  { path: "/api/runs/{run_id}/nodes/{node_id}", method: "get" },
  { path: "/api/runs/{run_id}/plan", method: "get" },
  { path: "/api/runtime-profiles", method: "get" },
  { path: "/api/runtime-profiles", method: "post" },
  { path: "/api/runtime-profiles/{profile_id}", method: "delete" },
  { path: "/api/runtime-profiles/{profile_id}", method: "get" },
  { path: "/api/runtime-profiles/{profile_id}", method: "patch" },
  { path: "/api/runtime-profiles/{profile_id}/probe", method: "get" },
  { path: "/api/runtime-profiles/{profile_id}/test", method: "post" },
  { path: "/api/schedules", method: "get" },
  { path: "/api/schedules", method: "post" },
  { path: "/api/schedules/{schedule_id}", method: "delete" },
  { path: "/api/schedules/{schedule_id}", method: "patch" },
  { path: "/api/schema/pipeline", method: "get" },
  { path: "/api/secrets", method: "get" },
  { path: "/api/secrets", method: "post" },
  { path: "/api/secrets/rotate-key", method: "post" },
  { path: "/api/secrets/{name}", method: "put" },
  { path: "/api/secrets/{secret_id}", method: "delete" },
  { path: "/api/v1/auth/audit", method: "get" },
  { path: "/api/v1/auth/login", method: "post" },
  { path: "/api/v1/auth/logout", method: "post" },
  { path: "/api/v1/auth/me", method: "get" },
  { path: "/api/v1/auth/oidc/callback", method: "get" },
  { path: "/api/v1/auth/oidc/config", method: "get" },
  { path: "/api/v1/auth/oidc/start", method: "get" },
  { path: "/api/v1/auth/users", method: "get" },
  { path: "/api/v1/auth/users", method: "post" },
  { path: "/api/v1/auth/users/{username}", method: "patch" },
  { path: "/api/v1/debug/diagnostics", method: "post" },
  { path: "/api/v1/debug/event-log/analyze", method: "post" },
  { path: "/api/v1/debug/plan/parse", method: "post" },
  { path: "/api/v1/debug/profile", method: "post" },
  { path: "/api/v1/debug/profile-diff", method: "post" },
  { path: "/api/v1/debug/redaction-preview", method: "post" },
  { path: "/api/v1/debug/schema-diff", method: "post" },
  { path: "/api/v1/debug/streaming/analyze", method: "post" },
  { path: "/api/v1/doctor", method: "get" },
  { path: "/api/v1/import/python", method: "post" },
  { path: "/api/v1/import/sql", method: "post" },
  { path: "/api/v1/operators", method: "get" },
  { path: "/api/v1/pipelines/{pipeline_id}", method: "get" },
  { path: "/api/v1/pipelines/{pipeline_id}", method: "put" },
  { path: "/api/v1/pipelines/{pipeline_id}/compatibility", method: "get" },
  { path: "/api/v1/pipelines/{pipeline_id}/preview", method: "post" },
  { path: "/api/v1/pipelines/{pipeline_id}/runs", method: "post" },
  { path: "/api/v1/pipelines/{pipeline_id}/validate", method: "post" },
  { path: "/api/v1/plugins", method: "get" },
  { path: "/api/v1/projects", method: "get" },
  { path: "/api/v1/projects", method: "post" },
  { path: "/api/v1/projects/clone", method: "post" },
  { path: "/api/v1/projects/{project_id}", method: "delete" },
  { path: "/api/v1/projects/{project_id}", method: "get" },
  { path: "/api/v1/projects/{project_id}", method: "patch" },
  { path: "/api/v1/projects/{project_id}/catalog", method: "get" },
  { path: "/api/v1/projects/{project_id}/code", method: "get" },
  { path: "/api/v1/projects/{project_id}/collaboration/capabilities", method: "get" },
  { path: "/api/v1/projects/{project_id}/debug/compare-runs", method: "post" },
  { path: "/api/v1/projects/{project_id}/debug/plan", method: "get" },
  { path: "/api/v1/projects/{project_id}/debug/row-trace/execute", method: "post" },
  { path: "/api/v1/projects/{project_id}/debug/row-trace/{node_id}", method: "get" },
  { path: "/api/v1/projects/{project_id}/debug/schema-timeline", method: "get" },
  { path: "/api/v1/projects/{project_id}/dry-run", method: "post" },
  { path: "/api/v1/projects/{project_id}/files", method: "get" },
  { path: "/api/v1/projects/{project_id}/files/directory", method: "post" },
  { path: "/api/v1/projects/{project_id}/files/rename", method: "post" },
  { path: "/api/v1/projects/{project_id}/files/{path}", method: "delete" },
  { path: "/api/v1/projects/{project_id}/files/{path}", method: "get" },
  { path: "/api/v1/projects/{project_id}/files/{path}", method: "put" },
  { path: "/api/v1/projects/{project_id}/generate", method: "post" },
  { path: "/api/v1/projects/{project_id}/generate-sql", method: "post" },
  { path: "/api/v1/projects/{project_id}/git/blob-diff", method: "get" },
  { path: "/api/v1/projects/{project_id}/git/branches", method: "delete" },
  { path: "/api/v1/projects/{project_id}/git/branches", method: "get" },
  { path: "/api/v1/projects/{project_id}/git/branches", method: "post" },
  { path: "/api/v1/projects/{project_id}/git/branches/switch", method: "post" },
  { path: "/api/v1/projects/{project_id}/git/checkout", method: "post" },
  { path: "/api/v1/projects/{project_id}/git/commit", method: "post" },
  { path: "/api/v1/projects/{project_id}/git/conflicts", method: "get" },
  { path: "/api/v1/projects/{project_id}/git/conflicts/resolve", method: "post" },
  { path: "/api/v1/projects/{project_id}/git/conflicts/{path}", method: "get" },
  { path: "/api/v1/projects/{project_id}/git/diff", method: "get" },
  { path: "/api/v1/projects/{project_id}/git/fetch", method: "post" },
  { path: "/api/v1/projects/{project_id}/git/graph-diff", method: "get" },
  { path: "/api/v1/projects/{project_id}/git/init", method: "post" },
  { path: "/api/v1/projects/{project_id}/git/log", method: "get" },
  { path: "/api/v1/projects/{project_id}/git/pull", method: "post" },
  { path: "/api/v1/projects/{project_id}/git/push", method: "post" },
  { path: "/api/v1/projects/{project_id}/git/remotes", method: "get" },
  { path: "/api/v1/projects/{project_id}/git/remotes", method: "post" },
  { path: "/api/v1/projects/{project_id}/git/repository", method: "get" },
  { path: "/api/v1/projects/{project_id}/git/review", method: "post" },
  { path: "/api/v1/projects/{project_id}/git/reviews", method: "get" },
  { path: "/api/v1/projects/{project_id}/git/stage", method: "post" },
  { path: "/api/v1/projects/{project_id}/git/stash", method: "get" },
  { path: "/api/v1/projects/{project_id}/git/stash", method: "post" },
  { path: "/api/v1/projects/{project_id}/git/status", method: "get" },
  { path: "/api/v1/projects/{project_id}/git/tags", method: "get" },
  { path: "/api/v1/projects/{project_id}/git/tags", method: "post" },
  { path: "/api/v1/projects/{project_id}/git/unstage", method: "post" },
  { path: "/api/v1/projects/{project_id}/history", method: "get" },
  { path: "/api/v1/projects/{project_id}/history/checkpoints", method: "post" },
  { path: "/api/v1/projects/{project_id}/history/{revision_id}", method: "get" },
  { path: "/api/v1/projects/{project_id}/history/{revision_id}/diff", method: "get" },
  { path: "/api/v1/projects/{project_id}/history/{revision_id}/restore", method: "post" },
  { path: "/api/v1/projects/{project_id}/history/{snapshot_id}", method: "get" },
  { path: "/api/v1/projects/{project_id}/history/{snapshot_id}/diff", method: "get" },
  { path: "/api/v1/projects/{project_id}/history/{snapshot_id}/restore", method: "post" },
  { path: "/api/v1/projects/{project_id}/import", method: "post" },
  { path: "/api/v1/projects/{project_id}/import/python", method: "post" },
  { path: "/api/v1/projects/{project_id}/import/sql", method: "post" },
  { path: "/api/v1/projects/{project_id}/pipeline", method: "get" },
  { path: "/api/v1/projects/{project_id}/pipeline", method: "put" },
  { path: "/api/v1/projects/{project_id}/pipelines", method: "get" },
  { path: "/api/v1/projects/{project_id}/pipelines", method: "post" },
  { path: "/api/v1/projects/{project_id}/preview", method: "post" },
  { path: "/api/v1/projects/{project_id}/quality/evaluate", method: "post" },
  { path: "/api/v1/projects/{project_id}/quality/suite/evaluate", method: "post" },
  { path: "/api/v1/projects/{project_id}/reconcile/python", method: "post" },
  { path: "/api/v1/projects/{project_id}/reconcile/sql", method: "post" },
  { path: "/api/v1/projects/{project_id}/retention/cleanup", method: "post" },
  { path: "/api/v1/projects/{project_id}/reviews", method: "get" },
  { path: "/api/v1/projects/{project_id}/runs", method: "get" },
  { path: "/api/v1/projects/{project_id}/runs", method: "post" },
  { path: "/api/v1/projects/{project_id}/runs/{run_id}/node-snapshots", method: "post" },
  { path: "/api/v1/projects/{project_id}/schedules", method: "get" },
  { path: "/api/v1/projects/{project_id}/schedules", method: "post" },
  { path: "/api/v1/projects/{project_id}/schedules/{schedule_id}/run-now", method: "post" },
  { path: "/api/v1/projects/{project_id}/tree", method: "get" },
  { path: "/api/v1/projects/{project_id}/validate", method: "post" },
  { path: "/api/v1/projects/{project_id}/validate-capabilities", method: "post" },
  { path: "/api/v1/projects/{project_id}/validate-model", method: "post" },
  { path: "/api/v1/runs/compare", method: "post" },
  { path: "/api/v1/runs/{run_id}", method: "get" },
  { path: "/api/v1/runs/{run_id}/artifacts", method: "get" },
  { path: "/api/v1/runs/{run_id}/artifacts/{artifact_path}", method: "get" },
  { path: "/api/v1/runs/{run_id}/cancel", method: "post" },
  { path: "/api/v1/runs/{run_id}/debug-bundle", method: "get" },
  { path: "/api/v1/runs/{run_id}/debug-bundle", method: "post" },
  { path: "/api/v1/runs/{run_id}/debug-bundle/preview", method: "get" },
  { path: "/api/v1/runs/{run_id}/events", method: "get" },
  { path: "/api/v1/runs/{run_id}/kubernetes/events", method: "get" },
  { path: "/api/v1/runs/{run_id}/kubernetes/logs", method: "get" },
  { path: "/api/v1/runs/{run_id}/kubernetes/probe", method: "get" },
  { path: "/api/v1/runs/{run_id}/kubernetes/status", method: "get" },
  { path: "/api/v1/runs/{run_id}/node-snapshots", method: "get" },
  { path: "/api/v1/runs/{run_id}/nodes/{node_id}", method: "get" },
  { path: "/api/v1/runs/{run_id}/plan", method: "get" },
  { path: "/api/v1/runtime-profiles", method: "get" },
  { path: "/api/v1/runtime-profiles", method: "post" },
  { path: "/api/v1/runtime-profiles/{profile_id}", method: "delete" },
  { path: "/api/v1/runtime-profiles/{profile_id}", method: "get" },
  { path: "/api/v1/runtime-profiles/{profile_id}", method: "patch" },
  { path: "/api/v1/runtime-profiles/{profile_id}/probe", method: "get" },
  { path: "/api/v1/runtime-profiles/{profile_id}/test", method: "post" },
  { path: "/api/v1/schedules", method: "get" },
  { path: "/api/v1/schedules", method: "post" },
  { path: "/api/v1/schedules/{schedule_id}", method: "delete" },
  { path: "/api/v1/schedules/{schedule_id}", method: "patch" },
  { path: "/api/v1/schema/pipeline", method: "get" },
  { path: "/api/v1/secrets", method: "get" },
  { path: "/api/v1/secrets", method: "post" },
  { path: "/api/v1/secrets/rotate-key", method: "post" },
  { path: "/api/v1/secrets/{name}", method: "put" },
  { path: "/api/v1/secrets/{secret_id}", method: "delete" },
  { path: "/health", method: "get" },
  { path: "/ready", method: "get" },
] as const;
export type OpenApiOperation = (typeof OPENAPI_OPERATIONS)[number];
